name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: build
        run: bazel build -c opt --platforms=//platforms:windows_x86_64 --verbose_failures //:dist_zip
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: bazel-bin/dist_zip.zip
